- hosts: all
  remote_user: "{{ newuser }}"
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - docker
    - swap
    - { role: docker_build, service: mysql, tags: [], exec_files: ['backup.sh', 'load_db.sh'] }
    - { role: docker_build, service: php, tags: [], exec_files: [] }
    - { role: docker_build, service: backend, tags: ['backend'], exec_files: ['site-normal', 'site-upgrade', 'site-upgrade', 'start-nginx.sh'] }
    - { role: docker_build, service: varnish, tags: [], exec_files: ['start-varnish.sh'] }
    - { role: docker_build, service: frontend, tags: [], exec_files: ['start-nginx.sh'] }
    - wordpress
    - load_wordpress
  tasks:
    - { include: tasks/docker-compose_rebuild.yml, service: data, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, service: frontend, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, service: varnish, tags: ['backend'] }
    - { include: tasks/docker-compose_rebuild.yml, service: backend, tags: ['backend'] }
    - { include: tasks/docker-compose_rebuild.yml, service: php, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, service: mysql, tags: [] }
    #remove the workpress install not in the container
    #bring up the containers and remove any unused containers
    - { include: tasks/docker_up.yml }

    - name: make sure mysql comes up
      pause: seconds=15

    - name: Set permissions in container
      shell: docker exec $(docker-compose -f {{ work_dir }}/docker-compose.yml ps -q backend) /site-normal

    - name: Load SQL backup
      command: chdir={{ work_dir }} {{ work_dir }}/move_sql_backup

    - name: Load blog backup database
      shell: docker exec $(docker-compose -f {{ work_dir }}/docker-compose.yml ps -q mysql) /load_db.sh
